# Generated by Django 3.1.5 on 2021-01-22 12:16

import address.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('data', models.JSONField(editable=False, null=True)),
                ('name', models.CharField(blank=True, default='(Unknown)', editable=False, max_length=100, verbose_name='Name')),
                ('email', models.EmailField(blank=True, editable=False, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', help_text='Your real name (may include spouse as family).', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('is_public', models.BooleanField(help_text="If you'd like to make your name public on the website, click here.")),
                ('is_teacher', models.BooleanField(help_text="If you're an educator, click here.")),
                ('is_medical', models.BooleanField(help_text="If you're a medical professional, click here.")),
                ('comments', models.TextField(blank=True, default='', help_text="If you'd like to add a public comment, add it here.  (Note: only productive, on-topic comments will be posted, you must use your real name, and you must set your overall status to 'public'.)", max_length=2000)),
                ('notes', models.TextField(blank=True, default='', help_text="If you'd like to add any private notes, add it here.  (Note: these are things you want us to know.)", max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('address', address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.address')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(0, 'New'), (10, 'Active'), (20, 'Closed'), (30, 'Merged')], default=0)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('kind', models.IntegerField(choices=[(0, 'New'), (10, 'Public'), (20, 'Private')], default=0)),
                ('level', models.IntegerField(blank=True, choices=[(510, 'Preschool'), (520, 'Elementary'), (530, 'Intermediate/Middle/Junior High'), (540, 'High School'), (550, 'Elementary-High Combination'), (555, 'Secondary'), (560, 'Adult'), (570, 'Ungraded')], null=True)),
                ('nces_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('low_grade', models.IntegerField(blank=True, choices=[(-1, 'Preschool'), (0, 'Kindergarten'), (1, 'First Grade'), (2, 'Second Grade'), (3, 'Third Grade'), (4, 'Fourth Grade'), (5, 'Fifth Grade'), (6, 'Sixth Grade'), (7, 'Seventh Grade'), (8, 'Eighth Grade'), (9, 'Ninth Grade'), (10, 'Tenth Grade'), (11, 'Eleventh Grade'), (12, 'Twelfth Grade')], null=True)),
                ('high_grade', models.IntegerField(blank=True, choices=[(-1, 'Preschool'), (0, 'Kindergarten'), (1, 'First Grade'), (2, 'Second Grade'), (3, 'Third Grade'), (4, 'Fourth Grade'), (5, 'Fifth Grade'), (6, 'Sixth Grade'), (7, 'Seventh Grade'), (8, 'Eighth Grade'), (9, 'Ninth Grade'), (10, 'Tenth Grade'), (11, 'Eleventh Grade'), (12, 'Twelfth Grade')], null=True)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(default='', max_length=255)),
                ('state', models.CharField(default='', max_length=255)),
                ('zipcode', models.CharField(blank=True, default='', max_length=255)),
                ('county', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=255)),
                ('website', models.URLField(blank=True, default='')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', help_text="Please add your student's name or initials.  Will remain private!", max_length=100)),
                ('grade', models.IntegerField(choices=[(-1, 'Preschool'), (0, 'Kindergarten'), (1, 'First Grade'), (2, 'Second Grade'), (3, 'Third Grade'), (4, 'Fourth Grade'), (5, 'Fifth Grade'), (6, 'Sixth Grade'), (7, 'Seventh Grade'), (8, 'Eighth Grade'), (9, 'Ninth Grade'), (10, 'Tenth Grade'), (11, 'Eleventh Grade'), (12, 'Twelfth Grade')], help_text='Grade')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='app.parent')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='app.school')),
            ],
        ),
    ]
