# Generated by Django 3.1.5 on 2021-01-25 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210124_0610'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parent',
            new_name='Account',
        ),
    ]
