# Generated by Django 3.1.5 on 2021-01-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210122_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='is_medical',
            field=models.BooleanField(blank=True, help_text="If you're a medical professional, click here."),
        ),
        migrations.AlterField(
            model_name='parent',
            name='is_public',
            field=models.BooleanField(blank=True, help_text="If you'd like to make your name public on the website, click here."),
        ),
        migrations.AlterField(
            model_name='parent',
            name='is_teacher',
            field=models.BooleanField(blank=True, help_text="If you're an educator, click here."),
        ),
    ]
