# Generated by Django 3.1.5 on 2021-01-27 16:32

from django.db import migrations, models
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210125_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('headers', models.TextField(blank=True, null=True, verbose_name='Headers')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('html', models.TextField(blank=True, null=True, verbose_name='HTML')),
                ('to_mailbox', models.TextField(verbose_name='To')),
                ('from_mailbox', models.TextField(verbose_name='From')),
                ('cc', models.TextField(blank=True, null=True, verbose_name='Carbon Copy')),
                ('subject', models.TextField(blank=True, null=True, verbose_name='Subject')),
                ('dkim', models.TextField(blank=True, null=True, verbose_name='DomainKeys Identified Mail')),
                ('SPF', models.TextField(blank=True, null=True, verbose_name='Sender Policy Framework')),
                ('envelope', models.JSONField(blank=True, default=dict, null=True, verbose_name='Envelope')),
                ('charsets', models.CharField(blank=True, max_length=255, null=True, verbose_name='Charsets')),
                ('spam_score', models.FloatField(blank=True, null=True, verbose_name='Spam score')),
                ('spam_report', models.TextField(blank=True, null=True, verbose_name='Spam report')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
            ],
        ),
    ]
