# Generated by Django 3.1.5 on 2021-01-27 17:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='SPF',
            new_name='spf',
        ),
        migrations.RemoveField(
            model_name='email',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='email',
            name='attachments',
            field=models.TextField(blank=True, null=True, verbose_name='Envelope'),
        ),
        migrations.AddField(
            model_name='email',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='email',
            name='sender_ip',
            field=models.TextField(blank=True, null=True, verbose_name='Sender IP'),
        ),
        migrations.AddField(
            model_name='email',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='cc',
            field=models.TextField(blank=True, null=True, verbose_name='cc'),
        ),
        migrations.AlterField(
            model_name='email',
            name='envelope',
            field=models.TextField(blank=True, null=True, verbose_name='Envelope'),
        ),
        migrations.AlterField(
            model_name='email',
            name='from_mailbox',
            field=models.TextField(blank=True, null=True, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='email',
            name='to_mailbox',
            field=models.TextField(blank=True, null=True, verbose_name='To'),
        ),
    ]
