# Generated by Django 3.1.5 on 2021-01-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210127_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='spf',
            new_name='SPF',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='from_mailbox',
            new_name='from_email',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='to_mailbox',
            new_name='to_email',
        ),
        migrations.AlterField(
            model_name='email',
            name='attachments',
            field=models.TextField(blank=True, null=True, verbose_name='Attachments'),
        ),
    ]
