# Generated by Django 3.1.5 on 2021-01-28 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_email_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='kind',
            field=models.IntegerField(blank=True, choices=[(100, 'Inbound'), (200, 'Outbound')], null=True),
        ),
    ]
